name: Go CI/CD Pipeline with Kubernetes Deployment

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  # ... (Previous pipeline stages)

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Docker login
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}

    - name: Pull Docker image
      run: docker pull my-go-app:latest

    - name: Set up Kubernetes context
      run: |
        # Adjust the kubeconfig path and context as needed
        kubectl config use-context my-cluster-context

    - name: Apply Kubernetes deployment
      run: |
        # Replace 'my-namespace' with the desired namespace in your cluster
        kubectl apply -f k8s/deployment.yaml -n my-namespace

    - name: Wait for deployment to be ready
      run: |
        kubectl rollout status deployment/my-go-app -n my-namespace