name: Go GraphQL CI/CD

on:
  push:
    branches:
      - main # Trigger workflow on pushes to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17 # Update the Go version as needed

    - name: Get dependencies
      run: go mod download

    - name: Run tests
      run: go test ./... -cover

    - name: Build application
      run: go build -o app

    - name: Deploy application
      uses: azure/actions-github-pages@v2
      with:
        publishPath: .
